---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову
  - Пользователь должен иметь возможность искать товары по категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары
  - Пользователь должен иметь возможность просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину
  - Пользователь должен иметь возможность просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования
  - Сайт должен быть оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
implicit:
  - Пользователь должен иметь возможность редактировать корзину
